#: kivy 2.3.0

#:include somniiaMonitor/view/body/homepage.kv
#:include somniiaMonitor/view/body/devices.kv
#:include somniiaMonitor/view/body/analysis.kv

#:include somniiaMonitor/view/customWidget/ctaButton.kv
#:include somniiaMonitor/view/customWidget/popup/bleSearchPopup.kv
##:include somniiaMonitor/view/customWidget/customGraph.kv
#:include somniiaMonitor/view/graph/inertialGraph.kv
#:include somniiaMonitor/view/graph/ekgGraph.kv
